#External Prior/Transform Input
extrinsics:
  # Published by GMSF
  worldFrame: "world_graph_msf"
  odomFrame: "odom_graph_msf"
  # Used for estimation
  imuFrame: "imu_link"       # IMU_CABIN_link           #Frame of IMU used in integrator - Used for lookup transform to lidarFrame
  baseLinkFrame: "imu_link"
  initializeZeroYawAndPositionOfFrame: "imu_link"

name_ids:
  fixedFrameAligned: "_graph_msf_aligned"  # Specifies what is the suffix of the aligned published fixed frames
  sensorFrameCorrected: "_graph_msf_corrected" # Specifies what is the suffix of the corrected published sensor frames
