/b2w_estimator_node:
  ros__parameters:
    #Common
    common_params:
      verbosity: 0                         #Debug Output, 0: only important events, 1: optimization duration, 2: added factors
      odomNotJumpAtStart: true   # Keep odom local at initialization and put global yaw/position into world->odom.
      publishStateBeforeYawPositionInit: false # Delay public odometry/TF/path until GNSS position + initial yaw are initialized
      logRealTimeStateToMemory: false  # Whether the real-time state should be logged to memory (for logging purposes)
      logLatencyAndUpdateDurationToMemory: false # Whether the latency and update duration should be logged to memory (for logging purposes)
