input_sources:
  elevation_mapping_sensor:
    type: pointcloud
    topic: /gt_box/livox/lidar
    queue_size: 1
    publish_on_update: true
    sensor_processor:
      type: laser
robot_base_frame_id: base
map_frame_id: offline_world
track_point_frame_id: box_base
sensor_frame_id: livox_lidar