#Common
common_params:
  verbosity: 0                         #Debug Output, 0: only important events, 1: optimization duration, 2: added factors
  logPlots: true

#Factor Graph
graph_params:
  imuRate: 100                             #Rate of IMU input (Hz)
  lidarRate: 5
  gnssRate: 20
  imuTimeOffset: 0.035 # Offset between IMU and LiDAR Measurements: can be determined with rqt_multiplot
  smootherLag: 6.0                         #Lag of fixed lag smoother[seconds], not needed for ISAM2
  additonalIterations: 0                  #Additional iterations of graph optimizer after update with new factors
  findUnusedFactorSlots: false
  enableDetailedResults: false
  usingLidarUnary: true
outlier_params:
  gnssOutlierThreshold: 0.3 # in meters, if jumping more than this, it is considered as abscent gnss, occures between two gnss measurements
  #graphUpdateThreshold: 0.2 # in meters, if jumping more than this, it is added to map->odom, and prediction model is used for odom->robot, occures between 2 imu messages
## Noise Parameters
noise_params:
  ### IMU
  #### Accelerometer
  accNoiseDensity: 7.225e-7                 #Continuous-time "Covariance" of accelerometer, microstrain: sigma^2=7.225e-7
  accBiasRandomWalk: 1.0e-06               #Continuous-time "Covariance" describing accelerometer bias random walk, default: 1.0e-06
  accBiasPrior: 0.0                        #Prior/starting value of accelerometer bias
  #### Gyro
  gyrNoiseDensity: 1.71e-08               #Continuous-time "Covariance" of gyroscope measurements, microstrain: sigma^2=1.71-08
  gyrBiasRandomWalk: 9.33e-08              #Continuous-time "Covariance" describing gyroscope bias random walk, default: 9.33e-08
  gyrBiasPrior: 0.0                        #Prior/starting value of gyroscope bias
  #### Preintegration
  integrationNoiseDensity: 1.0         #continuous-time "Covariance" describing integration uncertainty, default: 1.0e-06
  biasAccOmegaPreint: 1.0                 #covariance of bias used for preintegration, default: 1.0e-2
  ### LiDAR
  poseBetweenNoise: [ 10.0, 10.0, 10.0, 2.0, 2.0, 2.0 ] #Noise of add between factor -ORDER RPY(rad) - XYZ(meters)
  poseUnaryNoise: [ 1000.0, 1000.0, 1000.0, 2.0, 2.0, 2.0 ] # ORDER RPY(rad) - XYZ(meters) First tests:  [ 1000.0, 1000.0, 1000.0, 2.0, 2.0, 2.0 ]
  ### GNSS
  gnssPositionUnaryNoise: 1.0 #1.0e-02 # x, y, z of global position
  gnssHeadingUnaryNoise: 1.0 # x,y,z of heading vector
# Relinearization
relinearization_params:
  positionReLinTh: 5.0e-10                    #Position linearization threshold
  rotationReLinTh: 1.0e-10                    #Rotation linearization threshold
  velocityReLinTh: 1.0e-10                     #Linear Velocity linearization threshold
  accBiasReLinTh: 1.0e-10                      #Accelerometer bias linearization threshold
  gyrBiasReLinTh: 1.0e-10                      #Gyroscope bias linearization threshold
  relinearizeSkip: 1
  enableRelinearization: true
  evaluateNonlinearError: false
  cacheLinearizedFactors: true
  enablePartialRelinearizationCheck: true
