/**:
  ros__parameters:
    extrinsics:
      worldFrame: world
      odomFrame: odom
      imuFrame: imu_box_link
      baseLinkFrame: base_link
      initializeZeroYawAndPositionOfFrame: imu_box_link

    name_ids:
      referenceFrameAligned: _graph_msf_aligned
      sensorFrameCorrected: _graph_msf_corrected
