/smb_estimator_node:
  ros__parameters:
    #External Prior/Transform Input
    extrinsics:
      lidarOdometryFrame: "rslidar"        #LiDAR frame name - used to lookup LiDAR-to-ExternalSensor Frame
      wheelOdometryBetweenFrame: "base_link"      #Wheel odometry frame name - used to lookup Wheel-to-ExternalSensor Frame
      wheelLinearVelocityLeftFrame: "LH_WHEEL"  #Wheel linear velocity left frame name - used to lookup Wheel-to-ExternalSensor Frame
      wheelLinearVelocityRightFrame: "RH_WHEEL" #Wheel linear velocity right frame name - used to lookup Wheel-to-ExternalSensor Frame
      vioOdometryFrame: "base_link"        #VIO odometry frame name - used to lookup VIO-to-ExternalSensor Frame
