#External Prior/Transform Input
extrinsics:
  # Published by GMSF
  worldFrame: "world"
  odomFrame: "odom"
  # Used for estimation
  imuFrame: "ap20_imu" # "cpt7_imu", "ap20_imu", "ap20_imu" used to be "State" (in older bags)
  baseLinkFrame: "box_base"
  initializeZeroYawAndPositionOfFrame: "ap20_imu" #"cpt7_imu" # Initialize the yaw and position of the base frame to zero
                                             # this is just meant to avoid any jump after getting the first true measurements
name_ids:
  referenceFrameAligned: "_graph_msf_aligned"  # Specifies what is the suffix of the aligned published fixed frames
  sensorFrameCorrected: "_graph_msf_corrected" # Specifies what is the suffix of the corrected published sensor frames
