# Sensor Params
sensor_params:
  imuRate: 200.0                          # Rate of IMU input (Hz)
  createStateEveryNthImuMeasurement: 4    # Create a new state every n-th IMU measurement
  useImuSignalLowPassFilter: false        # If true, a low pass filter is applied to the IMU measurements
  imuLowPassFilterCutoffFreq: 30.0        # Cutoff frequency of the low pass filter
  imuBufferLength: 400
  imuTimeOffset: 0.0                      # Offset between IMU and LiDAR Measurements: can be determined with rqt_multiplot

# Initialization
initialization_params:
  estimateGravityFromImu: false           # If true, the gravity is estimated in the beginning using the IMU
  gravityMagnitude: 9.80600               # If estimateGravityFromImu is false, this value is used as gravity

# Factor Graph
graph_params:
  realTimeSmootherUseIsam: true
  realTimeSmootherLag: 2.0                # Lag of real-time fixed lag smoother[seconds]
  useAdditionalSlowBatchSmoother: true    # If true, a slower smoother is used in addition to the real-time smoother
  slowBatchSmootherUseIsam: false         # if false, then levenberg-marquardt is used for the slow batch smoother, NO EFFECT YET
  # Optimizer Config
  gaussNewtonWildfireThreshold: 0.001     # Threshold for the wildfire in the Gauss-Newton optimization
  minOptimizationFrequency: 1.0           # Minimum optimization frequency [Hz]
  maxOptimizationFrequency: 20.0          # Maximum optimization frequency [Hz], can be used to control computational load
  additionalOptimizationIterations: 0     # Additional iterations of graph optimizer after update with new factors
  findUnusedFactorSlots: true
  enableDetailedResults: false
  usingCholeskyFactorization: true        # CHOLESKY faster, QR numerically more stable
  usingBiasForPreIntegration: true        # If true, the bias is used during pre-integration
  # Alignment Parameters
  optimizeFixedFramePosesWrtWorld: true   # If true, the poses of the fixed frames are optimized w.r.t. world
  fixedFramePosesResetThreshold: 8.0      # Reset T_M_W if distance between initial guess and optimization are too big, [SE(3) distance]
  centerMeasurementsAtRobotPositionBeforeAlignment: true # If true, the measurements are centered before alignment
  # Extrinsic Calibration
  optimizeExtrinsicSensorToSensorCorrectedOffset: false     # If true, the extrinsic calibration is optimized

# Noise Parameters
noise_params:
  ## IMU
  ### Position
  #accNoiseDensity: 8.5e-04                 # Continuous-time Noise Amplitude Spectral Density (StdDev) [m/s^2/√Hz)], default=sqrt(7.84e-06)
  accNoiseDensity: 1.0e-02                 # TM: BMIO088 Spec Sheet: 175ug/sqrt(Hz) = 1.716e-03 m/s^2/sqrt(Hz) --> (10x more) --> 1.716e-02
  integrationNoiseDensity: 1.0e-03         # Continuous-time Noise Amplitude Spectral Density of integration uncertainty, default: sqrt(1.0e-07)
  use2ndOrderCoriolis: false               # Whether to use 2nd order coriolis effect
  ### Rotation
  #gyrNoiseDensity: 1.308e-04             # Continuous-time Noise Amplitude Spectral Density (StdDev) [rad/s/√Hz], default=sqrt(3.4906585e-07)
  gyrNoiseDensity: 1.0e-03               # TM_ BMI088 Spec Sheet: 0.014°/s/sqrt(Hz) = 2.443e-04 rad/s/sqrt(Hz) --> (10x more) --> 2.443e-03 
  omegaCoriolis: 1.07e-04                 # Coriolis effect, positive on northern hemisphere, 0 at the equator, default (central europe, Switzerland): 1.07e-04
  ### Bias
  accBiasRandomWalkNoiseDensity: 3.16e-02 # Default: sqrt(1.0e-03)
  gyrBiasRandomWalkNoiseDensity: 3.05e-02 # Default: sqrt(9.33e-04)
  biasAccOmegaInit: 3.16e-04              # Default: sqrt(1.0e-07)
  accBiasPrior: 0.0                       # Prior/starting value of accelerometer bias
  gyrBiasPrior: 0.0                       # Prior/starting value of gyroscope bias
  ## Initial State
  initialPositionNoiseDensity: 1.0e+01    # Prior/starting value of position
  initialOrientationNoiseDensity: 3.14    # Prior/starting value of orientation
  initialVelocityNoiseDensity: 1.0e+01    # Prior/starting value of velocity
  initialAccBiasNoiseDensity: 1.0e-01     # Prior/starting value of accelerometer bias
  initialGyroBiasNoiseDensity: 1.0e-01    # Prior/starting value of gyroscope bias

# Relinearization
relinearization_params:
  positionReLinTh: 1.0e-03                 # Position linearization threshold
  rotationReLinTh: 1.0e-03                 # Rotation linearization threshold
  velocityReLinTh: 1.0e-03                 # Linear Velocity linearization threshold
  accBiasReLinTh: 1.0e-03                  # Accelerometer bias linearization threshold
  gyrBiasReLinTh: 1.0e-03                  # Gyroscope bias linearization threshold
  fixedFrameReLinTh: 1.0e-03               # Fixed frame linearization threshold, ONLY USED IF optimizeFixedFramePosesWrtWorld is true
  displacementReLinTh: 1.0e-03             # Displacement linearization threshold, ONLY USED IF optimizeExtrinsicCalibration is true
  relinearizeSkip: 1                       # Re-linearization is skipped every n-th step, default: 10
  enableRelinearization: true              # Whether to use relinearization, default: true
  evaluateNonlinearError: true             # Whether to evaluate the nonlinear errorr before and after the update, default: false
  cacheLinearizedFactors: true             # Whether to cache the linearized factors, default: true
  enablePartialRelinearizationCheck: false # Whether potentially only parts of the tree needs to be relinearized, default: false
