# Sensor Params
sensor_params:
  lioOdometryRate: 5 # Output rate of compSLAM
  gnssRate: 20 # Rate of the GNSS
  useGnssYaw: false  # If true, the yaw is computed from both GNSS positions and added as a factor

# Alignment Parameters
alignment_params:
  initialSe3AlignmentNoiseDensity: [ 10.0, 10.0, 10.0, 10.0, 10.0, 10.0 ] # StdDev, ORDER RPY(rad) - XYZ(meters)
  lioSe3AlignmentRandomWalk: [ 0.05, 0.05, 0.05, 0.01, 0.01, 0.01 ] # StdDev, ORDER RPY(rad) - XYZ(meters)

# Noise Parameters
noise_params:
  ## LiDAR
  lioPoseUnaryNoiseDensity: [ 0.25, 0.25, 0.25, 0.05, 0.05, 0.05 ] # ORDER RPY(rad) - XYZ(meters)
  ## GNSS
  gnssPositionUnaryNoiseDensity: 0.04 # x, y, z of global position
  gnssHeadingUnaryNoiseDensity: 0.2   # radians
