#Common
Verbosity: 2                         #Debug Output, 0-disable, higher for more verbose output
scanPeriod: 0.1                          #Expected scan period for input pointcloud in seconds. Used of Distortion correction
ioRatio: 2                               #Ratio of publish rate of LaserOdometry w.r.t input PCL rate. LO is calculated for each PCL but published at slower rate to Mapping, default 2

#External Prior/Transform Input
mapFrame: map
odomFrame: odom
baseLinkFrame: BASE
lidarFrame: os_lidar                     #LiDAR frame name - used to lookup LiDAR-to-ExternalSensor Frame
imuCabinFrame: IMU_CABIN_link                 #Frame of IMU used in integrator - Used for lookup transform to lidarFrame
imuRooftopFrame: imu_box_link
cabinFrame: CABIN
leftGnssFrame: GNSS_L
rightGnssFrame: GNSS_R

#Factor Graph
lidarRate: 10
imuRate: 100                             #Rate of IMU input (Hz)
imuTimeOffset: 0.0 #seconds              #Offset between IMU and LiDAR Measurements - Depending on LiDAR timestamp first(+0.05) or last(-0.05)
accNoiseDensity: 7.225e-07                 #Continuous-time "Covariance" of accelerometer, microstrain: sigma^2=7.225e-7
accBiasRandomWalk: 1.0e-06               #Continuous-time "Covariance" describing accelerometer bias random walk, default: 1.0e-06
accBiasPrior: 0.0                        #Prior/starting value of accelerometer bias
gyrNoiseDensity: 1.71e-08               #Continuous-time "Covariance" of gyroscope measurements, microstrain: sigma^2=1.71-08
gyrBiasRandomWalk: 9.33e-08              #Continuous-time "Covariance" describing gyroscope bias random walk, default: 9.33e-08
integrationNoiseDensity: 1.0e-06         #continuous-time "Covariance" describing integration uncertainty, default: 1.0e-8
biasAccOmegaPreint: 1.0                 #covariance of bias used for preintegration, default: 1.0e-2
gyrBiasPrior: 0.0                        #Prior/starting value of gyroscope bias
smootherLag: 6.0                         #Lag of fixed lag smoother[seconds]
additonalIterations: 1                  #Additional iterations of graph optimizer after update with new factors
positionReLinTh: 5.0e-03                    #Position linearization threshold
rotationReLinTh: 1.0e-03                    #Rotation linearization threshold
velocityReLinTh: 1.0e-03                     #Linear Velocity linearization threshold
accBiasReLinTh: 1.0e-04                      #Accelerometer bias linearization threshold
gyrBiasReLinTh: 1.0e-04                      #Gyroscope bias linearization threshold
relinearizeSkip: 1
enableRelinearization: true
evaluateNonlinearError: false
cacheLinearizedFactors: true
findUnusedFactorSlots: false
enablePartialRelinearizationCheck: true
enableDetailedResults: false
poseBetweenNoise: [2.0e-02, 2.0e-02, 2.0e-02, 5.0e-01, 5.0e-01, 5.0e-01] #Noise of add between factor -ORDER RPY(rad) - XYZ(meters)
zeroMotionDetection: false                        #Detect and Add Zero Motion Factors(Zero delta Pose and Velocity)