#External Prior/Transform Input
extrinsics:
  mapFrame: enu
  odomFrame: odom
  baseLinkFrame: base
  lidarFrame: lidar        #LiDAR frame name - used to lookup LiDAR-to-ExternalSensor Frame
  imuFrame: imu_link       # IMU_CABIN_link           #Frame of IMU used in integrator - Used for lookup transform to lidarFrame
  gnssFrame: gps_new
