# Sensor Params
sensor_params:
  ## Config
  useLidarUnaryFactor: true
  useWheelOdometry: false
  useVioOdometry: false
  ## Rates
  lidarOdometryRate: 10
  wheelOdometryRate: 50
  vioOdometryRate: 50

# Noise Parameters
noise_params:
  ## LiDAR
  lidarPoseBetweenNoise: [ 5, 5, 5, 0.1, 0.1, 0.1 ] # ORDER RPY(rad) - XYZ(meters)
  lidarPoseUnaryNoise: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ] # ORDER RPY(rad) - XYZ(meters) First tests:  [ 1000.0, 1000.0, 1000.0, 2.0, 2.0, 2.0 ]
  ## Wheel
  wheelPoseBetweenNoise: [ 10.0, 10.0, 10.0, 1.0, 1.0, 0.1 ] # gnss [ 10.0, 10.0, 10.0, 2.0, 2.0, 2.0 ]
  ## VIO
  vioPoseBetweenNoise: [ 100.0, 100.0, 100.0, 0.1, 0.1, 0.1 ] # gnss [ 10.0, 10.0, 10.0, 2.0, 2.0, 2.0 ]
