# External Prior/Transform Input
extrinsics:
  lioOdometryFrame: hesai_lidar        #LiDAR frame name - used to lookup LiDAR-to-ExternalSensor Frame
  leggedOdometryFrame: base_link      #Tracked Legged odometry frame name
  gnssFrame: gps
