trajectoryAlignment:
  gnssRate: 10 # [Hz], rate of gnss measurements
  lidarRate: 10 # [Hz], rate of lidar odometry
  minimumDistanceHeadingInit: 4.0 # [m], minimal length of trajectory to get yaw between GNSS and Lidar trajectory
  noMovementDistance: 0.3 # [m], if measurements are below this distance and in time range, robot is considered standing
  noMovementTime: 1.0 # [s], if measurements is time range and below distance, robot is considered standing
alignment_params:
  initialSe3AlignmentNoiseDensity: [10.0, 10.0, 10.0, 10.0, 10.0 ,10.0] # [m], initial alignment noise density