#External Prior/Transform Input
extrinsics:
  lioOdometryFrame: base     ############ CARE HERE   #LiDAR frame name - used to lookup LiDAR-to-ExternalSensor Frame
  leggedOdometryFrame: base      #Tracked Legged odometry frame name
  gnssFrame: gps
