# Sensor Params
sensor_params:
  ## Config
  useGnss: true
  useLioOdometry: true
  useLioBetweenOdometry: false
  useVioOdometry: false
  useVioOdometryBetween: false
  useLeggedOdometryBetween: false
  useLeggedVelocityUnary: true
  useLeggedKinematics: false

  ## Rates
  lioOdometryRate: 10
  lioBetweenOdometryRate: 5
  vioOdometryRate: 10
  vioOdometryBetweenRate: 25
  leggedOdometryBetweenRate: 400
  leggedOdometryPoseDownsampleFactor: 40
  leggedOdometryVelocityRate: 20
  leggedOdometryVelocityDownsampleFactor: 1
  leggedKinematicsRate: 400
  leggedKinematicsDownsampleFactor: 10
  gnssRate: 20

# Alignment Parameters
alignment_params:
  initialSe3AlignmentNoiseDensity: [ 10.0, 10.0, 10.0, 10.0, 10.0, 10.0 ] # StdDev, ORDER RPY(rad) - XYZ(meters)
  lioSe3AlignmentRandomWalk: [ 0.2, 0.2, 0.2, 0.2, 0.2, 0.2 ] # StdDev, ORDER RPY(rad) - XYZ(meters)
  vioSe3AlignmentRandomWalk: [ 0.2, 0.2, 0.2, 0.2, 0.2, 0.2 ] # StdDev, ORDER RPY(rad) - XYZ(meters)

# Noise Parameters
noise_params:
  ## GNSS
  gnssPositionOutlierThreshold: 3.0 # meters
  ## LiDAR Odometry
  ## Unary Noise
  lioPoseUnaryNoiseDensity: [ 0.1, 0.1, 0.1, 0.1, 0.1, 0.1 ] # StdDev, ORDER RPY(rad) - XYZ(meters)
  ## Binary Noise
  lioPoseBetweenNoiseDensity: [ 0.05, 0.05, 0.05, 0.01, 0.01, 0.01 ] # StdDev, ORDER RPY(rad) - XYZ(meters)
  ## VIO Odometry
  vioPoseUnaryNoiseDensity: [ 0.1, 0.1, 0.1, 0.1, 0.1, 0.1 ] # StdDev, ORDER RPY(rad) - XYZ(meters)
  vioPoseBetweenNoiseDensity: [ 100.0, 100.0, 100.0, 0.1, 0.1, 0.1 ] # StdDev, ORDER RPY(rad) - XYZ(meters)
  ## Legged Odometry
  ## Between Noise
  legPoseBetweenNoiseDensity: [ 0.2, 0.2, 0.2, 0.1, 0.1, 0.1 ] # StdDev, ORDER RPY(rad) - XYZ(meters)
  ## Velocity Unary Noise
  legVelocityUnaryNoiseDensity: [ 0.05, 0.05, 0.05 ] # StdDev, ORDER XYZ(meters/sec)
  ## LegKinematics Noise
  legKinematicsFootPositionUnaryNoiseDensity: [ 0.01, 0.01, 0.01 ] # StdDev, XYZ(meters)
