#External Prior/Transform Input
extrinsics:
  worldFrame: world_graph_msf_
  mapFrame: map_graph_msf_
  odomFrame: odom_graph_msf_
  imuFrame: imu_link       # IMU_CABIN_link           #Frame of IMU used in integrator - Used for lookup transform to lidarFrame
  baseLinkFrame: base
  initializeZeroYawAndPositionOfFrame: imu_link
