/b2w_estimator_node:
  ros__parameters:
    trajectoryAlignment:
      gnssRate: 10.0 # [Hz], rate of gnss measurements
      lidarRate: 10.0 # [Hz], rate of lidar odometry
      minimumDistanceHeadingInit: 2.0 # [m], minimal length of trajectory to get yaw between GNSS and Lidar trajectory
      noMovementDistance: 0.1 # [m], if measurements are below this distance and in time range, robot is considered standing
      noMovementTime: 2.0 # [s], if measurements is time range and below distance, robot is considered standing
