/b2w_estimator_node:
  ros__parameters:
    #External Prior/Transform Input
    extrinsics:
      gnssFrame: "swiftnav-gnss"            #GNSS frame name - used to lookup GNSS-to-ExternalSensor Frame
      lidarOdometryFrame: "base"        #LiDAR frame name - used to lookup LiDAR-to-ExternalSensor Frame
      lidarBetweenFrame: "base"        #LiDAR frame name - used to lookup LiDAR-to-ExternalSensor Frame
      wheelOdometryBetweenFrame: "base"      #Wheel odometry frame name - used to lookup Wheel-to-ExternalSensor Frame
      wheelLinearVelocityLeftFrame: "LH_WHEEL"  #Wheel linear velocity left frame name - used to lookup Wheel-to-ExternalSensor Frame
      wheelLinearVelocityRightFrame: "RH_WHEEL" #Wheel linear velocity right frame name - used to lookup Wheel-to-ExternalSensor Frame
      vioOdometryFrame: "base"        #VIO odometry frame name - used to lookup VIO-to-ExternalSensor Frame
